# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07d548dbcf3ee00c0367fb66b4aa9e393074c456720260354eab18fc460c7324bd2c92d58b549e95741a7c0a985e4324429e1492029782933854cf42b8fbc4a4

test:
  secret_key_base: 869149d300bf612262e197f43afefc560c7fa53135a20f7f4e9439d6e53b98a67e7cb04b073229040c02ff33b1930db3a6595331ab509d68714423a1b9b40179

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
